version: 2.1
jobs:
  test:
    parameters:
      ruby_version:
        type: string
    resource_class: small
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
        environment:
          - S3_ENDPOINT=http://localhost:9000
          - S3_BUCKET=test
          - GCS_ENDPOINT=http://localhost:8080/
          - GCS_BUCKET=some-bucket
      - image: minio/minio:edge
        entrypoint: sh
        command: -c 'mkdir -p /data/test && /usr/bin/minio server /data --json'
      - image: fsouza/fake-gcs-server
        entrypoint: sh
        command: >
          -c 'mkdir -p /data/some-bucket &&
            /bin/fake-gcs-server -port 8080 -scheme http -external-url=http://localhost:8080 -public-host=localhost:8080 -filesystem-root /data
          '
    steps:
      - checkout
      - run:
          name: setup env
          command: gem install bundler && ruby -v && bundle -v
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Test syntax with rubocop
          command: bundle exec ./rubocop --display-style-guide --extra-details
      - run:
          name: Run tests
          command: bundle exec rspec
references:
  matrix_test: &matrix_test
    test:
      matrix:
        parameters:
          ruby_version: ["2.5", "2.6", "2.7", "3.0"]

workflows:
  version: 2
  build_and_test:
    jobs:
      - <<: *matrix_test
